### ISSUE TITLE
Wiki Home Page

### ISSUE THREAD

**Issue by aminbabar** [lavparker/EatingEasy#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

**Comment by aminbabar** [comment]
You do not need the EatingEasy page. That will be your home page.

**Comment by siascone** [comment]
Looks good. Be sure to add your heroku link to this page. When you do remove the space between the ending bracket and the opening parenthesis where you'll put the link
