### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by aminbabar** [lavparker/EatingEasy#2]
# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Heroku, and Production README.
  - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

**Comment by siascone** [comment]
Your primary features should be the following:
- MVP#3 - Restaurants - this will be index and show components for available restaurants
- MVP#4 - Reservations - this is its own feature separate from the restaurants
- MVP#5 -  Search - users can search for restaurants to make reservations
- MVP#6 - Ratings/Reviews

The descriptions you have look good. Please update MVPs 3-6 accordingly.

**Comment by lavparker** [comment]
Thank you, MVPs 3-6 have been updated.

**Comment by siascone** [comment]
looks good!
