### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by aminbabar** [lavparker/EatingEasy#6]
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by siascone** [comment]
Looks good, users will still be able to see all of the routes listed under If logged out: when the are logged in correct?

**Comment by lavparker** [comment]
This is correct. I've updated the routes to reflect the views for the logged in user.
